language: python
python:
  - "2.7"

before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get -qq update
- sudo apt-get install -y libgdal-dev=1.11.2+dfsg-1~exp2~trusty libevent-dev python-dev build-essential libyaml-dev libspatialindex-dev
# - sudo apt-get install -y libgdal1h libgdal1-dev python-gdal
- gdal-config --version


install:
  - pip install pygdal==1.11.2.3
  - pip install -r pip-required.txt
  - pip install -r pip-dev.txt

script:
  nosetests --with-coverage

after_success:
  - coveralls