language: python
python:
  - "2.7"


install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq software-properties-common
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libgdal1 libgdal1-dev python-dev build-essential libyaml-dev libspatialindex-dev
  # - sudo apt-get install -y libgdal1h libgdal1-dev python-gdal
  - gdal-config --version
  - pip install pygdal==1.11.2.3
  - pip install -r pip-required.txt
  - pip install -r pip-dev.txt

script:
  nosetests --with-coverage

after_success:
  - coveralls