language: python
python:
  - "2.7"

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libgdal-dev libevent-dev python-dev build-essential gdal-bin libyaml-dev libspatialindex-dev
- sudo apt-get install -y libgdal1h libgdal1-dev python-gdal
- gdal-config --version

install:
  - pip install pygdal==$( gdal-config --version )
  - pip install -r pip-required.txt
  - pip install -r pip-dev.txt

script:
  nosetests --with-coverage

after_success:
  - coveralls